version: '3.8'

services:
  fdm-community:
    build: .
    container_name: fdm-community
    restart: unless-stopped
    
    # Configuration réseau pour Synology
    ports:
      - "3001:3001"
    
    # Optimisations pour NAS Synology DS218+
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Variables d'environnement
    environment:
      - NODE_ENV=production
      - PORT=3001
      - NODE_OPTIONS=--max-old-space-size=512
      - UV_THREADPOOL_SIZE=4
      - DISCORD_TOKEN=${DISCORD_TOKEN:-MTM5MzQwNjQwNjg2NTk3NzQ3Nw.GVXMXj.apuAo9qscEnDI2G_5XoRpc1oEiGN6jygSb7LQ4}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID:-681602280893579342}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-FofoTheBest}
      - TZ=Europe/Paris
    
    # Volumes adaptés pour Synology (chemins standard)
    volumes:
      # Base de données persistante
      - ./data:/app/data
      # Logs persistants
      - ./logs:/app/logs
      # Cache pour optimiser les performances
      - fdm-cache:/tmp
    
    # Configuration réseau Synology
    networks:
      - fdm-network
    
    # Vérification de santé adaptée pour NAS
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/discord/stats"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Politique de redémarrage conservative pour NAS
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Sécurité renforcée
    security_opt:
      - no-new-privileges:true
    
    # Utilisateur non-root
    user: "1001:1001"

# Volumes nommés pour cache
volumes:
  fdm-cache:
    driver: local

# Réseau isolé
networks:
  fdm-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16